# Generated by Django 4.2.3 on 2023-07-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_receipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='user',
        ),
    ]
